### PR TITLE
Rails 3 and RSpec 2.4

### PR DESCRIPTION
**Pull request by jfelchner**
Had a project that required stub_model so I forked and changed the implementation to be the Rails 3 and RSpec 2 style.

I didn't bother with tests because I'm going to switch the project from mocha to RSpec mocking but I thought you might want to take this and run with it. :)

### CODE REVIEW

**Comment by mislav** [comment]
I would like to pull it but you basically rewrote all of it. Do you think this is a valid drop-in replacement for people experiencing issues with the new combination?

**Comment by jfelchner** [comment]
As far as backward compatibility (Rails 2 or Rspec 1), I'm certain these changes will not work.

The reason why there were so many changes is because I basically did what you did originally and that is; I grabbed the RSpec implementations and just modified the RSpec mocking methods to be the Mocha equivalents.

Because of that, this code should be good to go.

**Comment by tessro** [comment]
These fixes didn't work for me.  I had problems with `__proxy_model` and other internals being undefined.

I've extended your changes to resolve these issues and make all the existing specs pass.  I've also stubbed out a couple more common calls, like #to_key and errors#[].

See [paulrosania/rspec-rails-mocha](http://github.com/paulrosania/rspec-rails-mocha).

**Comment by jfelchner** [comment]
Paul, excellent job!  Sorry I didn't have time to do the specs.  I've been slammed lately.

Paul, have you submitted your own PR to Mislav?
Mislav, can we get Paul's changes into the official gem?

**Comment by mislav** [comment]
Merged changes, released new version.

@jfelchner @paulrosania: thanks for tackling this. You now have commit rights to my repo; see if your fixes close remaining issues and that the example in the README is still valid.

I don't use mocha lately so I can't test this out on my Rails 3 projects. You guys are now in charge :)

**Pull request closed without merging**
