### PR TITLE
Add missing require of rspec/core

### PR DESCRIPTION
**Pull request by solnic**
mocha.rb calls `RSpec.configure` so it's good to _not_ assume that rspec was already required and actually require it there. I just had a problem where my rails app was blowing up with "undefined method `configure' for RSpec:Module"

### CODE REVIEW

**Comment by jfelchner** [comment]
`rspec-rails` is already a dependency of the project and should be required automatically via Bundler.  Can you verify that it still throws the error when using `bundle exec rspec` instead of just `rspec`?

**Comment by solnic** [comment]
@jfelchner yeah I use bundler in this project and yet it was blowing up with or without `bundle exec`. Also it's just a good practice to require libs that you depend on, it's probably not safe to assume everybody will be using bundler in their projects (even though most of the people will probably do heh :))

**Comment by mislav** [comment]
I need to get rid of the `RSpec.configure` because recent RSpec version deprecated multiple calls to `configure`, meaning plugins shouldn't call `configure` anymore but should let the user do it once in their test prep.

**Comment by agarbutt** [comment]
I can confirm that this issue occurs when using bundler  ~> 1.1.0 and RSpec ~> 2.9.0
Any chance we can get this merged into master and a release so we dont have to monkey patch or depend on a git tag?

**Comment by mislav** [comment]
OK, I've merged this and released a new version.

But I don't plan on advancing this project further, as I don't use Mocha anymore.

**Pull request closed without merging**
